INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Antonio', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Francisco', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Manuel', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Penya', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Jose', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Pepe', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Maria', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Felipe', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Sergio', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Alejandra', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Carmen', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Laura', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Marina', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(4, 'Jorge', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Ana', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Alberto', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Zacarías', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Gustavo', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Lucia', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Paula', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(2, 'Enrique', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(2, 'Raquel', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(3, 'Paco', '1234');


INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (3, 'Nieto', 'ejemplo', 'Manuel', 'Malaga', 20, 'Hombre');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (5, 'Archilla', 'sitio', 'Jose', 'Almeria', 35, 'Hombre');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (10, 'Canterio', 'ejemplo', 'Alejandra', 'Malaga', 20, 'Mujer');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (7, 'Vera', 'sitio', 'Maria', 'Almeria', 35, 'Mujer');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (11, 'Romero', 'ejemplo', 'Carmen', 'Malaga', 20, 'Mujer');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, NOMBRE, CIUDAD, EDAD, SEXO) VALUES (14, 'Gómez', 'sitio', 'Jorge', 'Almeria', 35, 'Hombre');

INSERT INTO EVENTO (CREADOREVENTO, TITULO, DESCRIPCION, FECHA, FECHA_RESERVA, COSTE_ENTRADA, AFORO, MAX_NUM_ENTRADAS, ASIENTOSFIJOS, FILAS, COLUMNAS, MUSICA, AIRE_LIBRE, DEPORTE, TEATRO, GAMING, LECTURA, FORMACION, CONFERENCIA, BENEFICO, ARTE, TURISMO) VALUES (1, 'Concierto', 'Concierto de música clásica', '2021-05-16', '2021-04-15', 0, 120, 2, 0, 20, 6, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO EVENTO (CREADOREVENTO, TITULO, DESCRIPCION, FECHA, FECHA_RESERVA, COSTE_ENTRADA, AFORO, MAX_NUM_ENTRADAS, ASIENTOSFIJOS, FILAS, COLUMNAS, MUSICA, AIRE_LIBRE, DEPORTE, TEATRO, GAMING, LECTURA, FORMACION, CONFERENCIA, BENEFICO, ARTE, TURISMO) VALUES (1, 'Conferencia', 'Conferencia del nuevo software para desarrollo de bases de datos', '2021-05-16', '2021-04-15', 0, 120, 2, 0, 20, 6, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0);
INSERT INTO EVENTO (CREADOREVENTO, TITULO, DESCRIPCION, FECHA, FECHA_RESERVA, COSTE_ENTRADA, AFORO, MAX_NUM_ENTRADAS, ASIENTOSFIJOS, FILAS, COLUMNAS, MUSICA, AIRE_LIBRE, DEPORTE, TEATRO, GAMING, LECTURA, FORMACION, CONFERENCIA, BENEFICO, ARTE, TURISMO) VALUES (1, 'Cata de vinos', 'Cata de vinos nacionales', '2021-05-16', '2021-04-15', 0, 120, 2, 0, 20, 6, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0);

INSERT INTO EVENTO_USUARIO (USUARIO, IDEVENTO, FILA, COLUMNA, EVENTO) VALUES (3, 1, 3, 3, 1);
INSERT INTO EVENTO_USUARIO (USUARIO, IDEVENTO, FILA, COLUMNA, EVENTO) VALUES (11, 1, 3, 3, 1);
INSERT INTO EVENTO_USUARIO (USUARIO, IDEVENTO, FILA, COLUMNA, EVENTO) VALUES (10, 3, 3, 3, 3);

INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (21,1);
INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (21,5);
INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (21,6);
INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (22,10);
INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (22,15);
INSERT INTO CHAT (USUARIO1, USUARIO2) VALUES (22,20);

INSERT INTO MENSAJE (CHAT,TEXTO,FECHA_HORA, EMISOR) VALUES (1,'Hola, tengo una duda','2021-04-24 12:00:00',1);
INSERT INTO MENSAJE (CHAT,TEXTO,FECHA_HORA, EMISOR) VALUES (1,'Hola qué tal estás','2021-04-24 12:30:00',21);

INSERT INTO FILTRO(ANALISTAEVENTOS, NOMBRE, EDAD_LIM_INF, EDAD_LIM_SUP, SEXO, CIUDAD, ANYO, COSTE_ENTRADA, CATEGORIA, USUARIO) VALUES (23, 'Prueba1', 3, 7, 'hombre', 'Madrid', 2020, 0, 'musica', 1);
INSERT INTO FILTRO(ANALISTAEVENTOS, NOMBRE, EDAD_LIM_INF, EDAD_LIM_SUP, SEXO, CIUDAD, ANYO, COSTE_ENTRADA, CATEGORIA, USUARIO) VALUES (23, 'Prueba2', 15, 23, 'mujer', 'Madrid', 2020, 4, 'gaming', 1);
INSERT INTO FILTRO(ANALISTAEVENTOS, NOMBRE, EDAD_LIM_INF, EDAD_LIM_SUP, SEXO, CIUDAD, ANYO, COSTE_ENTRADA, CATEGORIA, USUARIO) VALUES (23, 'Prueba3', 24, 45, 'mujer', 'Malaga', 2020, 25, 'aire libre', 1);
INSERT INTO FILTRO(ANALISTAEVENTOS, NOMBRE, EDAD_LIM_INF, EDAD_LIM_SUP, SEXO, CIUDAD, ANYO, COSTE_ENTRADA, CATEGORIA, USUARIO) VALUES (23, 'Prueba4', 12, 27, 'otro', 'Malaga', 2020, 61, 'musica', 1);
INSERT INTO FILTRO(ANALISTAEVENTOS, NOMBRE, EDAD_LIM_INF, EDAD_LIM_SUP, SEXO, CIUDAD, ANYO, COSTE_ENTRADA, CATEGORIA, USUARIO) VALUES (23, 'Prueba5', 38, 72, 'hombre', 'Malaga', 2020, 21, 'arte', 1);