INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Antonio', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Francisco', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'Manuel', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(1, 'PeÃ±a', '1234');
INSERT INTO USUARIO (ROL, NICKNAME, PASSWORD) VALUES(0, 'Jose', '1234');

INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, CIUDAD, EDAD, SEXO) VALUES (3, 'Nieto', 'ejemplo', 'Malaga', 20, 'si');
INSERT INTO USUARIO_EVENTO (USUARIO, APELLIDO, DOMICILIO, CIUDAD, EDAD, SEXO) VALUES (5, 'Archilla', 'sitio', 'Almeria', 35, 'por favor');

INSERT INTO EVENTO (TITULO, DESCRIPCION, FECHA, FECHA_RESERVA, COSTE_ENTRADA, AFORO, MAX_NUM_ENTRADAS, MUSICA, AIRE_LIBRE, DEPORTE, TEATRO, GAMING) 
VALUES ('Hackers week', 'Cosa de informatica', '04/4/2021', '04/7/2022', 3, 43, 23, 0, 1, 0, 0, 1);
INSERT INTO EVENTO (TITULO, DESCRIPCION, FECHA, FECHA_RESERVA, COSTE_ENTRADA, AFORO, MAX_NUM_ENTRADAS, MUSICA, AIRE_LIBRE, DEPORTE, TEATRO, GAMING) 
VALUES ('Semana Santa', 'Cosa de santeritos', '02/4/2031', '04/7/2022', 45, 104, 17, 1, 1, 0, 0, 0);